use num_bigint::BigUint; // Importing big unsigned integers, i.e +ve numbers including zero

/// generator^x mod p
/// x = secret key
/// p = prime number of the finite group
/// output = n^exponent mod modulus
pub fn exponentiate(n: &BigUint, exponent: &BigUint, modulus: &BigUint) -> BigUint {
    n.modpow(exponent, modulus)
}

/// output = k - c * x mod q
/// k = random number generated by the prover
/// c = random number generated by the verifier
/// x = secret key
/// q = order of the finite group
pub fn solve(k: &BigUint, c: &BigUint, x: &BigUint, q: &BigUint) -> BigUint {
    if *k >= c * x {
        // case 1: k > c * x, then output is positive
        return (k - c * x).modpow(&BigUint::from(1u32), q);
    } else {
        // case 2: k < c * x, then output is negative
        // We have to do additive inverse for the correct value
        return q - ((c * x) - k).modpow(&BigUint::from(1u32), q);
    }
}

/// cond1: r1 == alpha^s * y1^c
/// cond2: r2 == beta^s * y2^c
/// where, s = k - c * x mod q
/// c = random number generated by the verifier
/// alpha & beta = generators of the finite cyclic group
/// (y1, y2) = (alpha^x, beta^x)
/// (r1, r2) = (alpha^k, beta^k)
pub fn verify(
    r1: &BigUint,
    r2: &BigUint,
    y1: &BigUint,
    y2: &BigUint,
    s: &BigUint,
    c: &BigUint,
    p: &BigUint,
    alpha: &BigUint,
    beta: &BigUint,
) -> bool {
    let cond1 = *r1 == alpha.modpow(s, p) * y1.modpow(c, p);
    let cond2 = *r2 == beta.modpow(s, p) * y2.modpow(c, p);
    cond1 && cond2
}
