use num_bigint::{BigUint, RandBigInt}; // Importing big unsigned integers, i.e +ve numbers including zero
use rand;

pub struct ZKP {
    p: BigUint,
    q: BigUint,
    alpha: BigUint,
    beta: BigUint,
}

impl ZKP {
    /// generator^x mod p
    /// x = secret key
    /// p = prime number of the finite group
    /// output = n^exponent mod modulus
    pub fn exponentiate(n: &BigUint, exponent: &BigUint, modulus: &BigUint) -> BigUint {
        n.modpow(exponent, modulus)
    }

    /// output = k - c * x mod q
    /// k = random number generated by the prover
    /// c = random number generated by the verifier
    /// x = secret key
    /// q = order of the finite group
    pub fn solve(&self, k: &BigUint, c: &BigUint, x: &BigUint) -> BigUint {
        // case 1: k > c * x, then output is positive
        if *k >= c * x {
            return (k - c * x).modpow(&BigUint::from(1u32), &self.q);
        }
        // case 2: k < c * x, then output is negative
        // We have to do additive inverse for the correct value
        return &self.q - ((c * x) - k).modpow(&BigUint::from(1u32), &self.q);
    }

    /// cond1: r1 == alpha^s * y1^c
    /// cond2: r2 == beta^s * y2^c
    /// where, s = k - c * x mod q
    /// c = random number generated by the verifier
    /// alpha & beta = generators of the finite cyclic group
    /// (y1, y2) = (alpha^x, beta^x)
    /// (r1, r2) = (alpha^k, beta^k)
    pub fn verify(
        &self,
        r1: &BigUint,
        r2: &BigUint,
        y1: &BigUint,
        y2: &BigUint,
        s: &BigUint,
        c: &BigUint,
    ) -> bool {
        let cond1 = *r1
            == (&self.alpha.modpow(s, &self.p) * y1.modpow(c, &self.p))
                .modpow(&BigUint::from(1u32), &self.p);
        let cond2 = *r2
            == (&self.beta.modpow(s, &self.p) * y2.modpow(c, &self.p))
                .modpow(&BigUint::from(1u32), &self.p);
        cond1 && cond2
    }

    pub fn generate_random_below(bound: &BigUint) -> BigUint {
        let mut rng = rand::thread_rng();
        rng.gen_biguint_below(bound)
    }
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn test_toy_example() {
        // public constants
        let zkp = ZKP {
            p: BigUint::from(23u32),
            q: BigUint::from(11u32),
            alpha: BigUint::from(4u32),
            beta: BigUint::from(9u32),
        };

        // prover side random numbers
        let x = BigUint::from(6u32);
        let k = BigUint::from(7u32);

        // verifier side random numbers
        let c = BigUint::from(4u32);

        let y1 = ZKP::exponentiate(&zkp.alpha, &x, &zkp.p);
        let y2 = ZKP::exponentiate(&zkp.beta, &x, &zkp.p);
        assert_eq!(y1, BigUint::from(2u32));
        assert_eq!(y2, BigUint::from(3u32));

        let r1 = ZKP::exponentiate(&zkp.alpha, &k, &zkp.p);
        let r2 = ZKP::exponentiate(&zkp.beta, &k, &zkp.p);
        assert_eq!(r1, BigUint::from(8u32));
        assert_eq!(r2, BigUint::from(4u32));

        let s = zkp.solve(&k, &c, &x);
        assert_eq!(s, BigUint::from(5u32));

        let result = zkp.verify(&r1, &r2, &y1, &y2, &s, &c);
        assert!(result);

        // fake solution should fail verification
        let x_fake = BigUint::from(7u32);
        let s_fake = zkp.solve(&k, &c, &x_fake);

        let result = zkp.verify(&r1, &r2, &y1, &y2, &s_fake, &c);
        assert!(!result);
    }

    #[test]
    fn test_toy_example_with_rng() {
        // public constants
        let zkp = ZKP {
            p: BigUint::from(23u32),
            q: BigUint::from(11u32),
            alpha: BigUint::from(4u32),
            beta: BigUint::from(9u32),
        };

        // prover side random numbers
        let x = BigUint::from(6u32);
        let k = ZKP::generate_random_below(&zkp.q);

        // verifier side random numbers
        let c = ZKP::generate_random_below(&zkp.q);

        let y1 = ZKP::exponentiate(&zkp.alpha, &x, &zkp.p);
        let y2 = ZKP::exponentiate(&zkp.beta, &x, &zkp.p);
        assert_eq!(y1, BigUint::from(2u32));
        assert_eq!(y2, BigUint::from(3u32));

        let r1 = ZKP::exponentiate(&zkp.alpha, &k, &zkp.p);
        let r2 = ZKP::exponentiate(&zkp.beta, &k, &zkp.p);

        let s = zkp.solve(&k, &c, &x);

        let result = zkp.verify(&r1, &r2, &y1, &y2, &s, &c);
        assert!(result);
    }
}
