use num_bigint::{BigUint, RandBigInt};
use rand; // Importing big unsigned integers, i.e +ve numbers including zero

pub struct ZKP {
    p: BigUint,
    q: BigUint,
    alpha: BigUint,
    beta: BigUint,
}

impl ZKP {
    /// generator^x mod p
    /// x = secret key
    /// p = prime number of the finite group
    /// output = n^exponent mod modulus
    pub fn exponentiate(n: &BigUint, exponent: &BigUint, modulus: &BigUint) -> BigUint {
        n.modpow(exponent, modulus)
    }

    /// output = k - c * x mod q
    /// k = random number generated by the prover
    /// c = random number generated by the verifier
    /// x = secret key
    /// q = order of the finite group
    pub fn solve(&self, k: &BigUint, c: &BigUint, x: &BigUint) -> BigUint {
        // case 1: k > c * x, then output is positive
        if *k >= c * x {
            return (k - c * x).modpow(&BigUint::from(1u32), &self.q);
        }
        // case 2: k < c * x, then output is negative
        // We have to do additive inverse for the correct value
        return &self.q - ((c * x) - k).modpow(&BigUint::from(1u32), &self.q);
    }

    /// cond1: r1 == alpha^s * y1^c
    /// cond2: r2 == beta^s * y2^c
    /// where, s = k - c * x mod q
    /// c = random number generated by the verifier
    /// alpha & beta = generators of the finite cyclic group
    /// (y1, y2) = (alpha^x, beta^x)
    /// (r1, r2) = (alpha^k, beta^k)
    pub fn verify(
        &self,
        r1: &BigUint,
        r2: &BigUint,
        y1: &BigUint,
        y2: &BigUint,
        s: &BigUint,
        c: &BigUint,
    ) -> bool {
        let cond1 = *r1
            == (&self.alpha.modpow(s, &self.p) * y1.modpow(c, &self.p))
                .modpow(&BigUint::from(1u32), &self.p);
        let cond2 = *r2
            == (&self.beta.modpow(s, &self.p) * y2.modpow(c, &self.p))
                .modpow(&BigUint::from(1u32), &self.p);
        cond1 && cond2
    }

    pub fn generate_random_below(bound: &BigUint) -> BigUint {
        let mut rng = rand::thread_rng();
        rng.gen_biguint_below(bound)
    }
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn test_toy_example() {
        // public constants
        let zkp = ZKP {
            p: BigUint::from(23u32),
            q: BigUint::from(11u32),
            alpha: BigUint::from(4u32),
            beta: BigUint::from(9u32),
        };

        // prover side random numbers
        let x = BigUint::from(6u32);
        let k = BigUint::from(7u32);

        // verifier side random numbers
        let c = BigUint::from(4u32);

        let y1 = ZKP::exponentiate(&zkp.alpha, &x, &zkp.p);
        let y2 = ZKP::exponentiate(&zkp.beta, &x, &zkp.p);
        assert_eq!(y1, BigUint::from(2u32));
        assert_eq!(y2, BigUint::from(3u32));

        let r1 = ZKP::exponentiate(&zkp.alpha, &k, &zkp.p);
        let r2 = ZKP::exponentiate(&zkp.beta, &k, &zkp.p);
        assert_eq!(r1, BigUint::from(8u32));
        assert_eq!(r2, BigUint::from(4u32));

        let s = zkp.solve(&k, &c, &x);
        assert_eq!(s, BigUint::from(5u32));

        let result = zkp.verify(&r1, &r2, &y1, &y2, &s, &c);
        assert!(result);

        // fake solution should fail verification
        let x_fake = BigUint::from(7u32);
        let s_fake = zkp.solve(&k, &c, &x_fake);

        let result = zkp.verify(&r1, &r2, &y1, &y2, &s_fake, &c);
        assert!(!result);
    }

    #[test]
    fn test_toy_example_with_rng() {
        // public constants
        let zkp = ZKP {
            p: BigUint::from(23u32),
            q: BigUint::from(11u32),
            alpha: BigUint::from(4u32),
            beta: BigUint::from(9u32),
        };

        // prover side random numbers
        let x = BigUint::from(6u32);
        let k = ZKP::generate_random_below(&zkp.q);

        // verifier side random numbers
        let c = ZKP::generate_random_below(&zkp.q);

        let y1 = ZKP::exponentiate(&zkp.alpha, &x, &zkp.p);
        let y2 = ZKP::exponentiate(&zkp.beta, &x, &zkp.p);
        assert_eq!(y1, BigUint::from(2u32));
        assert_eq!(y2, BigUint::from(3u32));

        let r1 = ZKP::exponentiate(&zkp.alpha, &k, &zkp.p);
        let r2 = ZKP::exponentiate(&zkp.beta, &k, &zkp.p);

        let s = zkp.solve(&k, &c, &x);

        let result = zkp.verify(&r1, &r2, &y1, &y2, &s, &c);
        assert!(result);
    }

    #[test]
    fn test_1024_bits_constants() {
        //
        //    Reference: https://www.rfc-editor.org/info/rfc5114/#section-2.1
        //
        //    The hexadecimal value of the prime is:
        //
        //    p = B10B8F96 A080E01D DE92DE5E AE5D54EC 52C99FBC FB06A3C6
        //        9A6A9DCA 52D23B61 6073E286 75A23D18 9838EF1E 2EE652C0
        //        13ECB4AE A9061123 24975C3C D49B83BF ACCBDD7D 90C4BD70
        //        98488E9C 219A7372 4EFFD6FA E5644738 FAA31A4F F55BCCC0
        //        A151AF5F 0DC8B4BD 45BF37DF 365C1A65 E68CFDA7 6D4DA708
        //        DF1FB2BC 2E4A4371
        //
        //    The hexadecimal value of the generator is:
        //
        //    g = A4D1CBD5 C3FD3412 6765A442 EFB99905 F8104DD2 58AC507F
        //        D6406CFF 14266D31 266FEA1E 5C41564B 777E690F 5504F213
        //        160217B4 B01B886A 5E91547F 9E2749F4 D7FBD7D3 B9A92EE1
        //        909D0D22 63F80A76 A6A24C08 7A091F53 1DBF0A01 69B6A28A
        //        D662A4D1 8E73AFA3 2D779D59 18D08BC8 858F4DCE F97C2A24
        //        855E6EEB 22B3B2E5
        //
        //    The generator generates a prime-order subgroup of size:
        //    q = F518AA87 81A8DF27 8ABA4E7D 64B7CB9D 49462353
        //
        let p = BigUint::from_bytes_be(&hex::decode("B10B8F96A080E01DDE92DE5EAE5D54EC52C99FBCFB06A3C69A6A9DCA52D23B616073E28675A23D189838EF1E2EE652C013ECB4AEA906112324975C3CD49B83BFACCBDD7D90C4BD7098488E9C219A73724EFFD6FAE5644738FAA31A4FF55BCCC0A151AF5F0DC8B4BD45BF37DF365C1A65E68CFDA76D4DA708DF1FB2BC2E4A4371").unwrap());
        let q = BigUint::from_bytes_be(
            &hex::decode("F518AA8781A8DF278ABA4E7D64B7CB9D49462353").unwrap(),
        );
        let alpha = BigUint::from_bytes_be(&hex::decode("A4D1CBD5C3FD34126765A442EFB99905F8104DD258AC507FD6406CFF14266D31266FEA1E5C41564B777E690F5504F213160217B4B01B886A5E91547F9E2749F4D7FBD7D3B9A92EE1909D0D2263F80A76A6A24C087A091F531DBF0A0169B6A28AD662A4D18E73AFA32D779D5918D08BC8858F4DCEF97C2A24855E6EEB22B3B2E5").unwrap());

        // beta = alpha ^ (any number)
        // The order of the group is prime and so every element is a generator
        // So, any number generated by the generator will be present in the group
        let beta = alpha.modpow(&ZKP::generate_random_below(&q), &p);

        let zkp = ZKP {
            p: p.clone(),
            q: q.clone(),
            alpha: alpha.clone(),
            beta: beta.clone(),
        };

        // prover side random numbers
        let x = ZKP::generate_random_below(&zkp.q);
        let k = ZKP::generate_random_below(&zkp.q);

        // verifier side random numbers
        let c = ZKP::generate_random_below(&zkp.q);

        let y1 = ZKP::exponentiate(&zkp.alpha, &x, &zkp.p);
        let y2 = ZKP::exponentiate(&zkp.beta, &x, &zkp.p);

        let r1 = ZKP::exponentiate(&zkp.alpha, &k, &zkp.p);
        let r2 = ZKP::exponentiate(&zkp.beta, &k, &zkp.p);

        let s = zkp.solve(&k, &c, &x);

        let result = zkp.verify(&r1, &r2, &y1, &y2, &s, &c);
        assert!(result);
    }

    #[test]
    fn test_2048_bits_constants() {
        //
        //    Reference: https://www.rfc-editor.org/info/rfc5114/#section-2.3
        //
        //    The hexadecimal value of the prime is:
        //
        //    p = 87A8E61D B4B6663C FFBBD19C 65195999 8CEEF608 660DD0F2
        //        5D2CEED4 435E3B00 E00DF8F1 D61957D4 FAF7DF45 61B2AA30
        //        16C3D911 34096FAA 3BF4296D 830E9A7C 209E0C64 97517ABD
        //        5A8A9D30 6BCF67ED 91F9E672 5B4758C0 22E0B1EF 4275BF7B
        //        6C5BFC11 D45F9088 B941F54E B1E59BB8 BC39A0BF 12307F5C
        //        4FDB70C5 81B23F76 B63ACAE1 CAA6B790 2D525267 35488A0E
        //        F13C6D9A 51BFA4AB 3AD83477 96524D8E F6A167B5 A41825D9
        //        67E144E5 14056425 1CCACB83 E6B486F6 B3CA3F79 71506026
        //        C0B857F6 89962856 DED4010A BD0BE621 C3A3960A 54E710C3
        //        75F26375 D7014103 A4B54330 C198AF12 6116D227 6E11715F
        //        693877FA D7EF09CA DB094AE9 1E1A1597
        //
        //    The hexadecimal value of the generator is:
        //
        //    g = 3FB32C9B 73134D0B 2E775066 60EDBD48 4CA7B18F 21EF2054
        //        07F4793A 1A0BA125 10DBC150 77BE463F FF4FED4A AC0BB555
        //        BE3A6C1B 0C6B47B1 BC3773BF 7E8C6F62 901228F8 C28CBB18
        //        A55AE313 41000A65 0196F931 C77A57F2 DDF463E5 E9EC144B
        //        777DE62A AAB8A862 8AC376D2 82D6ED38 64E67982 428EBC83
        //        1D14348F 6F2F9193 B5045AF2 767164E1 DFC967C1 FB3F2E55
        //        A4BD1BFF E83B9C80 D052B985 D182EA0A DB2A3B73 13D3FE14
        //        C8484B1E 052588B9 B7D2BBD2 DF016199 ECD06E15 57CD0915
        //        B3353BBB 64E0EC37 7FD02837 0DF92B52 C7891428 CDC67EB6
        //        184B523D 1DB246C3 2F630784 90F00EF8 D647D148 D4795451
        //        5E2327CF EF98C582 664B4C0F 6CC41659
        //
        //    The generator generates a prime-order subgroup of size:
        //    q = 8CF83642 A709A097 B4479976 40129DA2 99B1A47D 1EB3750B
        //        A308B0FE 64F5FBD3
        //
        let p = BigUint::from_bytes_be(&hex::decode("87A8E61DB4B6663CFFBBD19C651959998CEEF608660DD0F25D2CEED4435E3B00E00DF8F1D61957D4FAF7DF4561B2AA3016C3D91134096FAA3BF4296D830E9A7C209E0C6497517ABD5A8A9D306BCF67ED91F9E6725B4758C022E0B1EF4275BF7B6C5BFC11D45F9088B941F54EB1E59BB8BC39A0BF12307F5C4FDB70C581B23F76B63ACAE1CAA6B7902D52526735488A0EF13C6D9A51BFA4AB3AD8347796524D8EF6A167B5A41825D967E144E5140564251CCACB83E6B486F6B3CA3F7971506026C0B857F689962856DED4010ABD0BE621C3A3960A54E710C375F26375D7014103A4B54330C198AF126116D2276E11715F693877FAD7EF09CADB094AE91E1A1597").unwrap());
        let q = BigUint::from_bytes_be(
            &hex::decode("8CF83642A709A097B447997640129DA299B1A47D1EB3750BA308B0FE64F5FBD3")
                .unwrap(),
        );
        let alpha = BigUint::from_bytes_be(&hex::decode("3FB32C9B73134D0B2E77506660EDBD484CA7B18F21EF205407F4793A1A0BA12510DBC15077BE463FFF4FED4AAC0BB555BE3A6C1B0C6B47B1BC3773BF7E8C6F62901228F8C28CBB18A55AE31341000A650196F931C77A57F2DDF463E5E9EC144B777DE62AAAB8A8628AC376D282D6ED3864E67982428EBC831D14348F6F2F9193B5045AF2767164E1DFC967C1FB3F2E55A4BD1BFFE83B9C80D052B985D182EA0ADB2A3B7313D3FE14C8484B1E052588B9B7D2BBD2DF016199ECD06E1557CD0915B3353BBB64E0EC377FD028370DF92B52C7891428CDC67EB6184B523D1DB246C32F63078490F00EF8D647D148D47954515E2327CFEF98C582664B4C0F6CC41659").unwrap());

        // beta = alpha ^ (any number)
        // The order of the group is prime and so every element is a generator
        // So, any number generated by the generator will be present in the group
        let beta = alpha.modpow(&ZKP::generate_random_below(&q), &p);

        let zkp = ZKP {
            p: p.clone(),
            q: q.clone(),
            alpha: alpha.clone(),
            beta: beta.clone(),
        };

        // prover side random numbers
        let x = ZKP::generate_random_below(&zkp.q);
        let k = ZKP::generate_random_below(&zkp.q);

        // verifier side random numbers
        let c = ZKP::generate_random_below(&zkp.q);

        let y1 = ZKP::exponentiate(&zkp.alpha, &x, &zkp.p);
        let y2 = ZKP::exponentiate(&zkp.beta, &x, &zkp.p);

        let r1 = ZKP::exponentiate(&zkp.alpha, &k, &zkp.p);
        let r2 = ZKP::exponentiate(&zkp.beta, &k, &zkp.p);

        let s = zkp.solve(&k, &c, &x);

        let result = zkp.verify(&r1, &r2, &y1, &y2, &s, &c);
        assert!(result);
    }
}
